services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bartek
      - MONGO_INITDB_ROOT_PASSWORD=bartek
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bartek
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bartek
      - ME_CONFIG_MONGODB_SERVER=chat-mongodb
volumes:
  mongo: {}